### ISSUE TITLE
Yafti command fails with deprecation error

### ISSUE THREAD

**Issue by alexispurslane** [ublue-os/yafti#208]
OS image: silverblue-nvidia-userns-hardened:latest
OS version: 39.20240311.0

Command:

```
$ yafti -f /usr/share/ublue-os/firstboot/yafti.yml
```

Error:

```
Traceback (most recent call last):
  File "/usr/bin/yafti", line 5, in <module>
    from yafti.__main__ import app
  File "/usr/lib/python3.12/site-packages/yafti/__main__.py", line 25, in <module>
    from yafti.app import Yafti
  File "/usr/lib/python3.12/site-packages/yafti/app.py", line 25, in <module>
    from yafti.screen.window import Window
  File "/usr/lib/python3.12/site-packages/yafti/screen/window.py", line 8, in <module>
    from yafti.registry import SCREENS
  File "/usr/lib/python3.12/site-packages/yafti/registry.py", line 7, in <module>
    PLUGINS = {s.name: s.load()() for s in _plugins}
                       ^^^^^^^^
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yafti/plugin/flatpak.py", line 93, in <module>
    class Flatpak(Run):
  File "/usr/lib/python3.12/site-packages/yafti/plugin/flatpak.py", line 101, in Flatpak
    class Scheme(BaseModel):
  File "/usr/lib/python3.12/site-packages/yafti/plugin/flatpak.py", line 107, in Scheme
    @root_validator
     ^^^^^^^^^^^^^^
  File "/var/home/alexispurslane/.local/lib/python3.12/site-packages/pydantic/deprecated/class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/var/home/alexispurslane/.local/lib/python3.12/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.6/u/root-validator-pre-skip

```

**Comment by alexispurslane** [comment]
@marcoceppi 

> Can you include the yafti.yaml you're using? We have not yet migrated to pydantic version v2 but I know there are those interested in doing so.

Sure! It's just the file provided as stock with the image I was using: https://github.com/secureblue/secureblue/blob/live/config/files/usr/share/ublue-os/firstboot/yafti.yml

> Also, can you run pip freeze on your environment? This error looks like it's coming from a mismatched version of pydantic dependency installed.

Agreed on the pydantic version probably being mismatched. I'll run a pip freeze when I get a chance in a bit.

**Comment by abanna** [comment]
@alexispurslane I'll working on removing  or updating this in the near future.
